name: list all files

on: 
  workflow_dispatch:

jobs:
  List-all-items:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: list
        run: cat hello.txt
